apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: makeascene
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: false
