"""migration

Revision ID: 3cc5d92d78b6
Revises: 528b49d31a81
Create Date: 2026-06-14 18:45:44.828598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc5d92d78b6'
down_revision = '528b49d31a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('tags_parent_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['parent_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('parent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tags_parent_fkey'), 'tags', ['parent'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
