"""migration

Revision ID: 528b49d31a81
Revises: 2f250b38c75a
Create Date: 2026-06-14 18:02:58.393944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528b49d31a81'
down_revision = '2f250b38c75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tags', ['parent'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent')

    # ### end Alembic commands ###
