"""migration

Revision ID: 8176e30f54b8
Revises: 3cc5d92d78b6
Create Date: 2026-06-14 22:11:43.796538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8176e30f54b8'
down_revision = '3cc5d92d78b6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'role',
                sa.String(),
                nullable=True
            )
        )

    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
