"""migration

Revision ID: b128731b77f1
Revises: c6a5bb8b0259
Create Date: 2026-06-22 15:19:56.358317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b128731b77f1'
down_revision = 'c6a5bb8b0259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_account_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_account_application_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['site_account_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_account_application_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['site_account_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('site_account_application_sources')
    op.drop_table('site_account_application_contacts')
    op.drop_table('site_account_applications')
    # ### end Alembic commands ###
