"""migration

Revision ID: c6a5bb8b0259
Revises: e975f5126d23
Create Date: 2026-06-21 19:18:24.726726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a5bb8b0259'
down_revision = 'e975f5126d23'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'role',
            type_=sa.Integer(),
            postgresql_using="CASE role WHEN 'user' THEN 0 WHEN 'admin' THEN 2 ELSE 1 END"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
