"""Added tags

Revision ID: da73e40692ae
Revises: 17f836f1b1f4
Create Date: 2026-05-20 09:52:57.272620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da73e40692ae'
down_revision = '17f836f1b1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mature', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_preference', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('email_preference')
        batch_op.drop_column('mature')

    # ### end Alembic commands ###
