"""migration

Revision ID: f957e18bb581
Revises: b128731b77f1
Create Date: 2026-06-22 17:23:22.300154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f957e18bb581'
down_revision = 'b128731b77f1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('site_account_applications', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'account_name',
                sa.String(),
                nullable=False,
                server_default=''
            )
        )

    with op.batch_alter_table('site_account_applications', schema=None) as batch_op:
        batch_op.alter_column(
            'account_name',
            server_default=None
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_account_applications', schema=None) as batch_op:
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###
