from typing import Protocol

from app.domain_models.site_account.SiteAccount import SiteAccount
from app.domain_models.user import User


class SiteAccountRepoProtocol(Protocol):
    def __init__(self, session): ...

    def create_site_account(self, name: str, creator: User) -> bool: ...

    def get_site_account_by_name(self, name: str) -> SiteAccount | None: ...

    def get_site_account_by_id(self, site_account_id: int) -> SiteAccount | None: ...

    def update_site_account(self, site_account: SiteAccount) -> bool: ...

    def remove_site_account(self, site_account: SiteAccount) -> bool: ...
