from typing import Protocol

from app.domain_models.tags.blocked_tag import BlockedTag
from app.domain_models.tags.tag import Tag
from app.domain_models.user import User


class BlockedTagRepoProtocol(Protocol):
    def __init__(self, session): ...

    def create(self, user: User, tag: Tag) -> bool: ...

    def get_blocked_tags_by_user(self, user: User) -> list[BlockedTag]: ...

    def get_blocked_tags_by_tag(self, tag: Tag) -> list[BlockedTag]: ...

    def get_blocked_tag_by_id(self, blocked_tag_id: int) -> BlockedTag | None: ...

    def get_blocked_tag_by_user_and_tag(self, user: User, tag: Tag) -> BlockedTag | None: ...

    def remove_blocked_tag(self, blocked_tag: BlockedTag) -> bool: ...

    def update_blocked_tag(self, blocked_tag: BlockedTag) -> bool: ...
