from typing import Protocol

from app.domain_models.tags.saved_tag import SavedTag
from app.domain_models.tags.tag import Tag
from app.domain_models.user import User


class SavedTagRepoProtocol(Protocol):
    def __init__(self, session): ...

    def create(self, user: User, tag: Tag) -> bool: ...

    def get_saved_tags_by_user(self, user: User) -> list[SavedTag]: ...

    def get_saved_tags_by_tag(self, tag: Tag) -> list[SavedTag]: ...

    def get_saved_tag_by_id(self, saved_tag_id: int) -> SavedTag | None: ...

    def get_saved_tag_by_user_and_tag(self, user: User, tag: Tag) -> SavedTag | None: ...

    def remove_saved_tag(self, saved_tag: SavedTag) -> bool: ...

    def update_saved_tag(self, saved_tag: SavedTag) -> bool: ...
