from typing import Protocol

from app.domain_models.tags.tag import Tag


class TagRepoProtocol(Protocol):
    def __init__(self, session): ...

    def create_tag(self, name: str) -> bool: ...

    def get_tag_by_name(self, name: str) -> Tag | None: ...

    def get_tag_by_id(self, tag_id: int) -> Tag | None: ...

    def update_tag(self, tag: Tag) -> bool: ...

    def remove_tag(self, tag: Tag) -> bool: ...
